version: '3.8'
services:
    database:
        image: mariadb
        restart: on-failure
        ports:
            - 3310:3306
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
